matrix:
  include:
      - sudo: required
        language: python
        os: linux
        services:
        - docker
        env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 PLAT=manylinux1_x86_64 PYTHON_FLAVOR=cp27-cp27mu
      - sudo: required
        language: python
        os: linux
        services:
        - docker
        env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 PLAT=manylinux1_x86_64 PYTHON_FLAVOR=cp27-cp27m
      - sudo: required
        language: python
        os: linux
        services:
        - docker
        env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 PLAT=manylinux1_x86_64 PYTHON_FLAVOR=cp36-cp36m
      - sudo: required
        language: python
        os: linux
        services:
        - docker
        env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 PLAT=manylinux1_x86_64 PYTHON_FLAVOR=cp37-cp37m
      - sudo: required
        language: python
        os: linux
        services:
        - docker
        env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 PLAT=manylinux1_x86_64 PYTHON_FLAVOR=cp38-cp38
      - sudo: required
        language: python
        os: linux
        services:
        - docker
        env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PRE_CMD=linux32 PLAT=manylinux1_i686 PYTHON_FLAVOR=cp27-cp27mu
      - sudo: required
        language: python
        os: linux
        services:
        - docker
        env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PRE_CMD=linux32 PLAT=manylinux1_i686 PYTHON_FLAVOR=cp27-cp27m
      - sudo: required
        language: python
        os: linux
        services:
        - docker
        env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PRE_CMD=linux32 PLAT=manylinux1_i686 PYTHON_FLAVOR=cp36-cp36m
      - sudo: required
        language: python
        os: linux
        services:
        - docker
        env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PRE_CMD=linux32 PLAT=manylinux1_i686 PYTHON_FLAVOR=cp37-cp37m
      - sudo: required
        language: python
        os: linux
        services:
        - docker
        env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PRE_CMD=linux32 PLAT=manylinux1_i686 PYTHON_FLAVOR=cp38-cp38
      #- sudo: required
      #  language: python
      #  os: linux
      #  services:
      #  - docker
      #  env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64 PLAT=manylinux2010_x86_64
      - os: osx
        language: generic
        env: PYTHON=python2
      - os: osx
        language: generic
        env: PYTHON=python3
      - os: osx
        language: generic
        env: PYTHON=python3
        before_install:
            - brew update
            - brew upgrade python
            - python3 --version

install:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then docker pull $DOCKER_IMAGE; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then $PYTHON -m pip install wheel; fi

script:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then docker run --rm -e PLAT=$PLAT -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh ${PYTHON_FLAVOR} ; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then $PYTHON -m pip wheel $PWD -w $PWD/wheelhouse/ && $PYTHON -m pip install pythran-openblas --no-index -f $PWD/wheelhouse; fi
    - ls wheelhouse/

deploy:
  provider: releases
  api_key:
      secure: PdGI+Aqsx1gvYdXnpL72FHXDGx4wwiiBwzP9UZFE1lIXVMzdJRKrddGj4mlSVNTmANdhM1XzZ4F+mSu4attsVounM4goP6gR2uuX5uL2lZPHTaUOk2WKLl2tg7AYmCf0MG6IUGw8hk0I0I5IIPWc5lv8NSXV1ljtyEc5FplCGhBBpd7uK/NIUVtdqzw6WKB9GBHWAj7/fN60u+0CI18yOVX4O23Ut3Q5vKY6u85du5uNvpTeXK2ylD6qpVQ6Q87jDVuBUUrH08Qsqiph96uaUssESxNXJdBW9mdf3Trt6p59aqd7b5p4koX3fnNqpw+a1SAc+zdDk6xWzMrug6Gp2DGV8sflL0+EAzM+/l8fYXMRD3njQf+0OBS786CmR7Vufr6K/sXi+tb789m7qgYccdqjjOZvHZG5oVf3rkhHIYNdykOzqP/O/N77INch4xC9c5i7+9pRyAzz6xxCvLDAUauEt3jFT/zUtyG3jfcNgEiCZ3Vp5/Hn/dsjoNy3FKArEkS0RLuE7J/J5q6PIoWGzVwiXVm4mu89s+0Z4YUg/8whM5COxVJGX1GPeHrZmC1et49ADs7iDr+oKKD8diAICVf4rL+lpalSEalkxEydTTtwt1jkst5UwbytbzGLqHE00ofUzVKkbVZJTCUBUmn7DUzold0ikSk7zoaf8T65x/E=
  overwrite: true
  skip_cleanup: true
  file_glob: true
  file: wheelhouse/*
  on:
      all_branches: true
